name: lightrag
channels:
  - conda-forge
  - microsoft
dependencies:
  - python=3.11
  - pip
  - ipywidgets
  - faiss-gpu
  - microsoft::playwright
  - pip:
      - crawl4ai<=0.4.248
      - lightrag-hku<=1.1.7
      - pipmaster